/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PhdRouteImport } from './routes/phd'
import { Route as MasterRouteImport } from './routes/master'
import { Route as FreeEduTechBooksRouteImport } from './routes/free-edu-tech-books'
import { Route as EduTechResearchRouteImport } from './routes/edu-tech-research'
import { Route as BooksRouteImport } from './routes/books'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PhdRoute = PhdRouteImport.update({
  id: '/phd',
  path: '/phd',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterRoute = MasterRouteImport.update({
  id: '/master',
  path: '/master',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeEduTechBooksRoute = FreeEduTechBooksRouteImport.update({
  id: '/free-edu-tech-books',
  path: '/free-edu-tech-books',
  getParentRoute: () => rootRouteImport,
} as any)
const EduTechResearchRoute = EduTechResearchRouteImport.update({
  id: '/edu-tech-research',
  path: '/edu-tech-research',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/books': typeof BooksRoute
  '/edu-tech-research': typeof EduTechResearchRoute
  '/free-edu-tech-books': typeof FreeEduTechBooksRoute
  '/master': typeof MasterRoute
  '/phd': typeof PhdRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/books': typeof BooksRoute
  '/edu-tech-research': typeof EduTechResearchRoute
  '/free-edu-tech-books': typeof FreeEduTechBooksRoute
  '/master': typeof MasterRoute
  '/phd': typeof PhdRoute
  '/research': typeof ResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/books': typeof BooksRoute
  '/edu-tech-research': typeof EduTechResearchRoute
  '/free-edu-tech-books': typeof FreeEduTechBooksRoute
  '/master': typeof MasterRoute
  '/phd': typeof PhdRoute
  '/research': typeof ResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/books'
    | '/edu-tech-research'
    | '/free-edu-tech-books'
    | '/master'
    | '/phd'
    | '/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/books'
    | '/edu-tech-research'
    | '/free-edu-tech-books'
    | '/master'
    | '/phd'
    | '/research'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/books'
    | '/edu-tech-research'
    | '/free-edu-tech-books'
    | '/master'
    | '/phd'
    | '/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BooksRoute: typeof BooksRoute
  EduTechResearchRoute: typeof EduTechResearchRoute
  FreeEduTechBooksRoute: typeof FreeEduTechBooksRoute
  MasterRoute: typeof MasterRoute
  PhdRoute: typeof PhdRoute
  ResearchRoute: typeof ResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phd': {
      id: '/phd'
      path: '/phd'
      fullPath: '/phd'
      preLoaderRoute: typeof PhdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/master': {
      id: '/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof MasterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-edu-tech-books': {
      id: '/free-edu-tech-books'
      path: '/free-edu-tech-books'
      fullPath: '/free-edu-tech-books'
      preLoaderRoute: typeof FreeEduTechBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu-tech-research': {
      id: '/edu-tech-research'
      path: '/edu-tech-research'
      fullPath: '/edu-tech-research'
      preLoaderRoute: typeof EduTechResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BooksRoute: BooksRoute,
  EduTechResearchRoute: EduTechResearchRoute,
  FreeEduTechBooksRoute: FreeEduTechBooksRoute,
  MasterRoute: MasterRoute,
  PhdRoute: PhdRoute,
  ResearchRoute: ResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
